-- Register bound status intents without grants or approval policies.
ALTER TABLE business_agent_master_intents DROP CONSTRAINT business_agent_master_intents_kind_check, ADD CONSTRAINT business_agent_master_intents_kind_check CHECK(kind IN ('core_master_creation_intent','core_master_update_intent','product_master_creation_intent','product_master_update_intent','core_master_status_intent','product_master_status_intent'));
ALTER TABLE business_document_approval_requests DROP CONSTRAINT business_document_approval_requests_document_type_check, ADD CONSTRAINT business_document_approval_requests_document_type_check CHECK(document_type IN ('sales_order','purchase_order','shipment','goods_receipt','inventory_opening','customer_receipt','supplier_payment','receivable_allocation_intent','payable_allocation_intent','customer_receipt_reversal_intent','supplier_payment_reversal_intent','receivable_allocation_reversal_intent','payable_allocation_reversal_intent','sales_order_cancellation_intent','purchase_order_cancellation_intent','shipment_reversal_intent','goods_receipt_reversal_intent','inventory_opening_reversal_intent','sales_return','purchase_return','sales_return_inspection_intent','purchase_return_dispatch_intent','purchase_return_acknowledgment_intent','sales_return_cancellation_intent','purchase_return_cancellation_intent','sales_return_reversal_intent','purchase_return_reversal_intent','inventory_count_creation_intent','inventory_count_submission_intent','inventory_count_posting_intent','inventory_count_cancellation_intent','crm_creation_intent','crm_update_intent','crm_followup_intent','core_master_creation_intent','core_master_update_intent','product_master_creation_intent','product_master_update_intent','core_master_status_intent','product_master_status_intent'));
ALTER TABLE agent_read_delegations DROP CONSTRAINT agent_read_delegations_approval_document_type_check, ADD CONSTRAINT agent_read_delegations_approval_document_type_check CHECK(approval_document_type IS NULL OR approval_document_type IN ('sales_order','purchase_order','shipment','goods_receipt','inventory_opening','customer_receipt','supplier_payment','receivable_allocation_intent','payable_allocation_intent','customer_receipt_reversal_intent','supplier_payment_reversal_intent','receivable_allocation_reversal_intent','payable_allocation_reversal_intent','sales_order_cancellation_intent','purchase_order_cancellation_intent','shipment_reversal_intent','goods_receipt_reversal_intent','inventory_opening_reversal_intent','sales_return','purchase_return','sales_return_inspection_intent','purchase_return_dispatch_intent','purchase_return_acknowledgment_intent','sales_return_cancellation_intent','purchase_return_cancellation_intent','sales_return_reversal_intent','purchase_return_reversal_intent','inventory_count_creation_intent','inventory_count_submission_intent','inventory_count_posting_intent','inventory_count_cancellation_intent','crm_creation_intent','crm_update_intent','crm_followup_intent','core_master_creation_intent','core_master_update_intent','product_master_creation_intent','product_master_update_intent','core_master_status_intent','product_master_status_intent'));
INSERT INTO business_iam.permissions(id,capability,resource_type,action,obligations,risk_level)
SELECT gen_random_uuid(),kind||':'||action,kind,action,
CASE WHEN action='approve' THEN '["fresh_signed_chat_command"]'::jsonb ELSE '[]'::jsonb END,'high'
FROM (VALUES ('core_master_status_intent'),('product_master_status_intent')) kinds(kind)
CROSS JOIN (VALUES ('create'),('approve')) actions(action)
ON CONFLICT(capability) DO NOTHING;
